/**
 * Config Schema API Routes
 * 
 * Provides endpoints for retrieving the dynamically generated configuration schema.
 * The schema is generated from reference.cfg and defines parameter types, validation
 * rules, and UI metadata.
 * 
 * @module backend/api/config-schema
 */

import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

import { Router, Request, Response } from 'express';

import { apiPaths } from '../../shared/api/constants';
import type { ConfigSchema } from '../../shared/previous-config/schema-types';

// Define __dirname for ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const router = Router();

// Cache for schema (loaded once on startup)
let schemaCache: ConfigSchema | null = null;

/**
 * Load schema from generated JSON file
 * 
 * Reads schema.json from shared directory. This file is generated by
 * the generate-config-schema.sh script during build or manually.
 */
function loadSchema(): ConfigSchema {
  if (schemaCache) {
    return schemaCache;
  }

  try {
    // Try multiple paths to handle both development and production
    let schemaPath = join(__dirname, '../../shared/previous-config/schema.json');
    try {
      const schemaContent = readFileSync(schemaPath, 'utf-8');
      schemaCache = JSON.parse(schemaContent) as ConfigSchema;
      return schemaCache;
    } catch {
      // Try alternative path for built app
      schemaPath = join(process.cwd(), 'shared/previous-config/schema.json');
      const schemaContent = readFileSync(schemaPath, 'utf-8');
      schemaCache = JSON.parse(schemaContent) as ConfigSchema;
      return schemaCache;
    }
  } catch (error) {
    console.error('Failed to load config schema:', error);
    throw new Error('Config schema not found. Run "npm run generate:schema" first.');
  }
}

/**
 * GET /api/config/schema
 * 
 * Returns the complete configuration schema including all sections and parameters.
 * 
 * Response format:
 * {
 *   "sections": {
 *     "SectionName": {
 *       "name": "SectionName",
 *       "displayName": "Section Name",
 *       "translationKey": "configEditor.sections.SectionName",
 *       "sfSymbol": "gearshape.fill",
 *       "parameters": [...]
 *     }
 *   }
 * }
 */
router.get(apiPaths.ConfigSchema.get.relative, (request: Request, response: Response) => {
  try {
    const schema = loadSchema();
    response.json(schema);
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    response.status(500).json({
      error: 'Failed to load configuration schema',
      details: errorMessage
    });
  }
});

/**
 * GET /api/config/schema/sections
 * 
 * Returns only section names and metadata (without parameters).
 * Useful for building section navigation or overview.
 */
router.get(apiPaths.ConfigSchema.getSections.relative, (request: Request, response: Response) => {
  try {
    const schema = loadSchema();
    const sections = Object.values(schema.sections).map(section => ({
      name: section.name,
      displayName: section.displayName,
      translationKey: section.translationKey,
      sfSymbol: section.sfSymbol
    }));
    response.json({ sections });
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    response.status(500).json({
      error: 'Failed to load configuration schema',
      details: errorMessage
    });
  }
});

/**
 * GET /api/config/schema/sections/:sectionName
 * 
 * Returns schema for a specific section including all its parameters.
 * 
 * @param sectionName - Name of the section (e.g., "ConfigDialog", "System")
 */
router.get(apiPaths.ConfigSchema.getSection.relative, (request: Request, response: Response) => {
  try {
    const schema = loadSchema();
    const { sectionName } = request.params;
    
    const section = schema.sections[sectionName];
    if (!section) {
      response.status(404).json({
        error: 'Section not found',
        section: sectionName
      });
      return;
    }
    
    response.json(section);
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    response.status(500).json({
      error: 'Failed to load configuration schema',
      details: errorMessage
    });
  }
});

/**
 * POST /api/config/schema/reload
 * 
 * Clears the schema cache and reloads from file.
 * Useful during development or after schema regeneration.
 */
router.post(apiPaths.ConfigSchema.reload.relative, (request: Request, response: Response) => {
  try {
    schemaCache = null;
    const schema = loadSchema();
    response.json({
      success: true,
      message: 'Schema reloaded successfully',
      sectionCount: Object.keys(schema.sections).length
    });
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    response.status(500).json({
      error: 'Failed to reload configuration schema',
      details: errorMessage
    });
  }
});

export default router;
