steps:
  frontend-test:
    image: node:18
    commands:
      - npm ci
      - npm run lint
      - npm run typecheck
      - npm run test:frontend
    artifacts:
      - coverage/cobertura-coverage.xml
    when:
      - event: push
      - event: pull_request

  backend-test:
    image: node:18
    commands:
      - npm ci
      - npm run lint
      - npm run typecheck
      - npm run test:backend
    artifacts:
      - coverage/cobertura-coverage.xml
    when:
      - event: push
      - event: pull_request

  update-badges:
    image: alpine:latest
    commands:
      - apk add --no-cache bash findutils gawk sed
      - chmod +x scripts/update_badges.sh
      - ./scripts/update_badges.sh
    when:
      - event: push
      - branch: main