name: Update Badges

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CODEBERG_TOKEN }}

      - name: Update badges
        run: |
          chmod +x update_badges.sh
          ./update_badges.sh

      - name: Commit and push changes
        run: |
          if git diff --quiet README.md; then
            echo "Keine Änderungen an README.md"
          else
            git config --global user.email "ci@codeberg.org"
            git config --global user.name "Forgejo Actions"
            git add README.md
            git commit -m "Update badges via Actions"
            git push
          fi