/**
 * Generated font list
 * This file is auto-generated by scripts/generate-fontlist.ts
 * Do not edit manually!
 */

/**
 * Available fonts in the application
 */
export const PA_AVAILABLE_FONTS = ['Barlow Semi Condensed', 'Exo2', 'Roboto Flex', 'Share Tech'] as const;

export type PAFontFamily = (typeof PA_AVAILABLE_FONTS)[number];
