/**
 * CFG ↔ JSON Converter
 * 
 * Converts between Previous emulator CFG file format and JSON representation.
 * Uses the configuration schema for type information and validation.
 * 
 * @module backend/config-schema/converter
 */

import type { ConfigSchema } from '../../shared/previous-config/schema-types';

import { parseCfgFile, type RawConfigData } from './config-parser';

/**
 * Generic configuration object (JSON representation)
 * 
 * Structure: { SectionName: { parameterName: value, ... }, ... }
 */
export type ConfigObject = Record<string, Record<string, string | number | boolean>>;

/**
 * Convert CFG file content to JSON object
 * 
 * Parses CFG file and converts values to appropriate types based on schema.
 * 
 * @param cfgContent Raw CFG file content
 * @param schema Configuration schema (for type conversion)
 * @returns Typed configuration object
 * 
 * @example
 * const cfgContent = fs.readFileSync('config.cfg', 'utf-8');
 * const schema = loadSchema();
 * const config = cfgToJson(cfgContent, schema);
 * // config = { ConfigDialog: { bShowDialog: true }, System: { nMachineType: 0 } }
 */
export function cfgToJson(cfgContent: string, schema: ConfigSchema): ConfigObject {
  const rawConfig = parseCfgFile(cfgContent);
  const config: ConfigObject = {};

  for (const section of rawConfig.sections) {
    const sectionSchema = schema.sections.find(s => s.name === section.name);
    if (!sectionSchema) {
      // Section not in schema - skip or store as-is
      console.warn(`Section not found in schema: ${section.name}`);
      continue;
    }

    config[section.name] = {};

    for (const param of section.parameters) {
      const paramSchema = sectionSchema.parameters.find(p => p.name === param.name);
      if (!paramSchema) {
        console.warn(`Parameter not found in schema: ${section.name}.${param.name}`);
        continue;
      }

      // Convert value based on schema type
      config[section.name][param.name] = convertStringToType(
        param.value,
        paramSchema.type
      );
    }
  }

  return config;
}

/**
 * Convert JSON object to CFG file content
 * 
 * Generates CFG file format from configuration object.
 * Includes section headers and comments for readability.
 * 
 * @param config Configuration object
 * @param schema Configuration schema (for ordering and metadata)
 * @returns CFG file content
 * 
 * @example
 * const config = { ConfigDialog: { bShowDialog: true }, System: { nMachineType: 0 } };
 * const schema = loadSchema();
 * const cfgContent = jsonToCfg(config, schema);
 * // Returns properly formatted CFG file content
 */
export function jsonToCfg(config: ConfigObject, schema: ConfigSchema): string {
  const lines: string[] = [];

  // Header comment
  lines.push('# Previous Emulator Configuration');
  lines.push('# Generated by Previous Admin');
  lines.push('');

  // Iterate through sections in schema order
  for (const sectionSchema of schema.sections) {
    const sectionData = config[sectionSchema.name];

    if (!sectionData) {
      // Section not in config - skip
      continue;
    }

    // Section header
    lines.push(`[${sectionSchema.name}]`);

    // Parameters
    for (const paramSchema of sectionSchema.parameters) {
      const value = sectionData[paramSchema.name];
      
      if (value === undefined) {
        // Parameter not in config - use default
        lines.push(`${paramSchema.name} = ${convertTypeToString(paramSchema.default)}`);
      } else {
        lines.push(`${paramSchema.name} = ${convertTypeToString(value)}`);
      }
    }

    lines.push(''); // Empty line between sections
  }

  return lines.join('\n');
}

/**
 * Convert string value to typed value based on parameter type
 * 
 * @param value String value from CFG file
 * @param type Parameter type from schema
 * @returns Converted value with appropriate type
 */
function convertStringToType(
  value: string,
  type: string
): string | number | boolean {
  const trimmedValue = value.trim();

  switch (type) {
    case 'boolean':
      // Accept TRUE/FALSE, true/false, 1/0
      return (
        trimmedValue.toUpperCase() === 'TRUE' ||
        trimmedValue === '1' ||
        trimmedValue === 'true'
      );

    case 'number':
    case 'range':
      // Parse as integer or float
      return trimmedValue.includes('.') 
        ? parseFloat(trimmedValue) 
        : parseInt(trimmedValue, 10);

    case 'enum':
    case 'string':
    default:
      // Return as string
      return trimmedValue;
  }
}

/**
 * Convert typed value to string for CFG file
 * 
 * @param value Typed value
 * @returns String representation for CFG file
 */
function convertTypeToString(value: string | number | boolean): string {
  if (typeof value === 'boolean') {
    return value ? 'TRUE' : 'FALSE';
  }
  
  return String(value);
}

/**
 * Parse CFG file to raw data structure
 * 
 * Re-export for convenience
 */
export function parseCfg(cfgContent: string): RawConfigData {
  return parseCfgFile(cfgContent);
}
