/**
 * Symbol Validation Utility
 * 
 * Validates that all symbol references in section-symbols.json
 * correspond to actual available SF Symbol files.
 * 
 * Generated by: scripts/generate-config-schema.sh
 */

import { readFileSync } from 'fs';

/**
 * Extract available SF Symbol names from the available-symbols.ts file
 * @returns Array of available symbol values
 */
export function getAvailableSymbols(): string[] {
  // When run from scripts, the current working directory is the project root
  const availableSymbolsFile = 'frontend/components/sf-symbols/available-symbols.ts';
  
  try {
    const content = readFileSync(availableSymbolsFile, 'utf-8');
    const matches = content.match(/= '([^']+)',/g) || [];
    return matches.map(m => m.replace(/= '|',/g, ''));
  } catch {
    // File not found or read error - skip validation
    console.warn('⚠️  Could not read available symbols file, skipping validation');
    return [];
  }
}

/**
 * Validate that all symbols in section-symbols.json are available
 * @param symbolMapping The section-to-symbol mapping
 * @returns { valid: boolean; errors: string[] }
 */
export function validateSymbols(symbolMapping: Record<string, string>): { valid: boolean; errors: string[] } {
  const availableSymbols = getAvailableSymbols();
  
  if (availableSymbols.length === 0) {
    return { valid: true, errors: [] };
  }
  
  const errors: string[] = [];
  
  for (const [section, symbol] of Object.entries(symbolMapping)) {
    if (!availableSymbols.includes(symbol)) {
      errors.push(`❌ Section "${section}" references unavailable symbol "${symbol}"`);
    }
  }
  
  return { valid: errors.length === 0, errors };
}

/**
 * Report validation results
 */
export function reportValidationResults(result: { valid: boolean; errors: string[] }): void {
  if (result.valid) {
    console.log('✅ All symbol mappings are valid (symbols exist in SVG files)');
  } else {
    console.error('❌ Invalid symbol mappings detected:');
    result.errors.forEach(error => console.error(error));
    throw new Error('Symbol validation failed');
  }
}
