/**
 * Re-export fonts from generated list
 * The list is generated by scripts/generate-fontlist.ts from actual font files
 */
export { PA_AVAILABLE_FONTS as AVAILABLE_FONTS, type PAFontFamily as FontFamily } from '@frontend/lib/fonts';

